# Generated by Django 3.0 on 2020-08-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchi_wk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchimdl',
            name='fld_Binary',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='buchimdl',
            name='fld_Duration',
            field=models.DurationField(null=True, verbose_name='holds the time period'),
        ),
        migrations.AlterField(
            model_name='buchimdl',
            name='fld_File',
            field=models.FileField(null=True, upload_to='C:\\Users\\buchi\\source\\repos\\buchiDjango3\\buchiDjango3\\_upload_files', verbose_name='File upload fields'),
        ),
        migrations.AlterField(
            model_name='buchimdl',
            name='fld_FilePath',
            field=models.FilePathField(path='C:\\Users\\buchi\\source\\repos\\buchiDjango3\\buchiDjango3\\_upload_files'),
        ),
    ]
